manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: keysmash
      url: https://github.com/ReFil/refil-zmk-behaviour-modules
      revision: keysmash
    - name: awawa
      url: https://github.com/ReFil/refil-zmk-behaviour-modules
      revision: awawa
  self:
    path: config
